print("Welcome to Mad Libs. This is the GWC addiion.")
name = input("Please input your name ")
location = input("Please input a location ")
adjective1 = input("Please input an adjective ")
noun1 = input("Please input a noun ") 
adjective2 = input("Please input an adjective ")
noun2 = input("Please input a noun ") 
name2 = input("Please input another name ")
noun3 = input("Please input a clothing item ") 
adjective4 = input("Please input an adjective ")
noun4 = input("Please input a food ") 
adjective5 = input("Please input an adjective ")
noun5 = input("Please input a noun ") 
print("Thank you! Please wait as I input all your words into my story!")
print("Today, " + name + " will start her first day at GWC in " + location + " where she will be learning " + adjective1 + " coding on a special " + noun1 + ".")
print( "At " + location + ", she met her " + adjective2 + " instructors. " + "Sitting on " + noun2 + ", " + name + " started to wait for the other kids to arrive.")
print("Then, a girl wearing really " + adjective4 + " " + noun3 + " came up to " + name + " and introduced herself as " + name2 + ".")
print("The two hit it off and ate " + noun4 + " by the " + adjective5 + " " + noun5 + ".")
